### ISSUE TITLE
Reference implementation seems to have syntax issue

### ISSUE THREAD

**Issue by garethmcc** [hola/challenge_str_search#5]
When running the reference implementation with Node, I get the following error:

substrings.forEach(s=>{
                        ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by andreogle** [comment]
What version of Node are you running?

Arrow functions are _mostly_ supported in Node 5
https://kangax.github.io/compat-table/es6/

**Comment by garethmcc** [comment]
Just installed NodeJS 5.5.0. All is well. As you were. Nothing to see here.
